group_dict =    {
                    'Cots & Cot Beds - Bedroom': 'Slatted Divan Bases & Foundations - HC1I',
                    'Cabinet Lighting - Bedroom': 'Under-Cabinet Lights - HCHQ',
                    'Kids Accessories - Kids Room': "Children's Furniture - HC2D",
                    'Dining Tables - Dining Rooms': 'Dining Tables - HC3A',
                    'Coffee Tables - Living Rooms': 'Coffee Tables - HC6Q',
                    'Sideboards - Dining Rooms': 'Sideboards - HC3C',
                    'TV Units - Living Rooms': 'TV Stands & Multimedia Centres - HC45',
                    'Cabinets - Dining Rooms': 'Cabinets - HC61',
                    'Sliding Wardrobes - Bedroom': 'Bedroom Wardrobes - HC1E',
                    'Kids Wall Shelving - Kids Room': 'Shelves - HC2Y',
                    'Wall Shelving - Living Rooms': 'Wall Units - HC6V',
                    'Wardrobes - Bedroom': 'Bedroom Wardrobes - HC1E',
                    'Kids Wardrobes - Kids Room': 'Wardrobes - HC35',
                    'Chest of Drawers - Bedroom': 'Chest of Drawers - HC1U',
                    'Bedside Cabinet - Bedroom': 'Bedside Tables - HC1S',
                    'Shoe Storage Cabinet  - Bedroom': 'Shoe Racks - HC3O',
                    'Shoe Storage Cabinet - Living Rooms': 'Shoe Racks - HC3O',
                    'Desks - Home Office': 'Desks - HC50',
                    'Storage - Home Office': 'Shelving & Storage - HC4Q',
                    'Bookcases - Home Office': 'Bookcases - HC4D',
                    'Professional Office - Home Office': 'Home Office Furniture - HC4B',
                    'Kids Toy Storage - Kids Room': 'Toy Chests & Boxes - HC34',
                    'Beds - Bedroom': 'Bed Frames - HC1L',
                    'Kids Beds - Kids Room': 'Beds - HC2F',
                    'Kids Cabinets - Kids Room': 'Cabinets - HC2J',
                    'Kids Bunk Beds - Kids Room': 'Beds - HC2F',
                    'Kids High Sleeper Beds - Kids Room': 'Beds - HC2F',
                    'Kids Day Beds - Kids Room': 'Beds - HC2F',
                    'Kids Mid Sleeper Beds - Kids Room': 'Beds - HC2F',
                    'Sofas - Sofas and Arm Chairs': 'Sofas & Couches - HC6O',
                    'Cabinets - Living Rooms': 'Cabinets - HC61',
                    'Dressing Table - Bedroom': 'Dressing Tables - HC1V',
                    'Arm Chairs - Sofas and Arm Chairs': 'Armchairs - HC68',
                    'Mirrors - Bedroom': 'Mirrors - HCD9',
                    'Dining Chairs - Dining Rooms': 'Dining Chairs - HC38',
                    'Footstool - Sofas and Arm Chairs': 'Footstools & Ottomans - HC6H',
                    'Bed Slats - Bedroom': 'Bed Slats - HC1H'
                }